import groq from "groq";

export const publishedCaseStudiesQuery = groq`*[_type == "caseStudy"] | order(coalesce(publishedDate, date, _createdAt) desc, _createdAt desc, title asc) {
  _id,
  _type,
  _createdAt,
  _updatedAt,
  title,
  "slug": slug.current,
  description,
  category,
  publishedDate,
  date,
  status,
  liveUrl,
  liveProjectUrl,
  prototypeUrl,
  twitterUrl,
  whatsappNumber,
  client,
  industry,
  nextSteps,
  tasks,
  tags,
  brandLogo{
    asset->{
      _ref,
      url,
      extension,
      mimeType,
      metadata{
        dimensions
      }
    }
  },
  heroImage{
    asset->{
      _ref,
      url,
      extension,
      mimeType,
      metadata{
        dimensions
      }
    }
  },
  overviewImage{
    asset->{
      _ref,
      url,
      extension,
      mimeType,
      metadata{
        dimensions
      }
    }
  },
  overviewText,
  overviewDescription,
  sections[]{
    _key,
    _type,
    title,
    heading,
    body,
    description,
    text,
    alt,
    caption,
    columns,
    headers,
    videoUrl,
    audioUrl,
    embedUrl,
    code,
    language,
    rows[]{
      cells
    },
    image{
      asset->{
        _ref,
        url,
        extension,
        mimeType,
        metadata{
          dimensions
        }
      }
    },
    poster{
      asset->{
        _ref,
        url,
        extension,
        mimeType,
        metadata{
          dimensions
        }
      }
    },
    video{
      asset->{
      _ref,
      url,
      extension,
      mimeType,
      metadata{
        dimensions
      }
    }
    },
    audio{
      asset->{
      _ref,
      url,
      extension,
      mimeType,
      metadata{
        dimensions
      }
    }
    },
    images[]{
      alt,
      caption,
      asset->{
        _ref,
        url,
        extension,
        mimeType,
        metadata{
          dimensions
        }
      },
      image{
        asset->{
          _ref,
          url,
          extension,
          mimeType,
          metadata{
            dimensions
          }
        }
      }
    },
    frames[]{
      alt,
      caption,
      asset->{
        _ref,
        url,
        extension,
        mimeType,
        metadata{
          dimensions
        }
      },
      image{
        asset->{
          _ref,
          url,
          extension,
          mimeType,
          metadata{
            dimensions
          }
        }
      }
    }
  },
  overview,
  stats[]{
    value,
    label
  },
  role,
  tools,
  timeline,
  problems[]{
    title,
    description
  },
  researchText,
  researchImages[]{
    asset->{
      _ref,
      url,
      extension,
      mimeType,
      metadata{
        dimensions
      }
    }
  },
  wireframeText,
  wireframeImages[]{
    asset->{
      _ref,
      url,
      extension,
      mimeType,
      metadata{
        dimensions
      }
    }
  },
  prototypeText,
  prototypeImages[]{
    asset->{
      _ref,
      url,
      extension,
      mimeType,
      metadata{
        dimensions
      }
    }
  },
  results[]{
    metric,
    description
  },
  finalImages[]{
    asset->{
      _ref,
      url,
      extension,
      mimeType,
      metadata{
        dimensions
      }
    }
  }
}`;

export const publishedLegacyProjectsQuery = groq`*[_type == "project" && coalesce(status, "published") == "published"] | order(coalesce(date, _createdAt) desc, _createdAt desc, title asc) {
  _id,
  _type,
  _createdAt,
  _updatedAt,
  ...,
  "slug": slug.current
}`;

export const publishedProjectsQuery = publishedCaseStudiesQuery;

export const publishedPostsQuery = groq`*[_type == "post"] | order(coalesce(date, _createdAt) desc, _createdAt desc, title asc) {
  _id,
  _type,
  _createdAt,
  _updatedAt,
  title,
  "slug": coalesce(slug.current, slug),
  excerpt,
  date,
  read_time,
  tag,
  thumb_url,
  "thumbnail": coalesce(
    thumb_url,
    mainImage.asset->url,
    mainImage.url,
    thumbnail.asset->url,
    thumbnail.url,
    image.asset->url,
    image.url,
    heroImage.asset->url,
    heroImage.url
  ),
  author{
    name,
    initials,
    avatar_url
  },
  content_blocks[]{
    ...,
    _type,
    "url": coalesce(url, src, image.asset->url, image.url, asset->url),
    images[]{
      ...,
      "url": coalesce(url, src, image.asset->url, image.url, asset->url)
    }
  },
  next_post{
    title,
    "slug": coalesce(slug.current, slug),
    excerpt,
    date,
    read_time,
    tag,
    thumb_url,
    "thumbnail": coalesce(
      thumb_url,
      mainImage.asset->url,
      mainImage.url,
      thumbnail.asset->url,
      thumbnail.url,
      image.asset->url,
      image.url,
      heroImage.asset->url,
      heroImage.url
    ),
    author{
      name,
      initials,
      avatar_url
    }
  },
  sections[]{
    _key,
    _type,
    title,
    heading,
    body,
    description,
    text,
    alt,
    caption,
    columns,
    headers,
    videoUrl,
    audioUrl,
    embedUrl,
    code,
    language,
    rows[]{
      cells
    },
    image{
      asset->{
      _ref,
      url,
      extension,
      mimeType,
      metadata{
        dimensions
      }
    }
    },
    poster{
      asset->{
      _ref,
      url,
      extension,
      mimeType,
      metadata{
        dimensions
      }
    }
    },
    video{
      asset->{
      _ref,
      url,
      extension,
      mimeType,
      metadata{
        dimensions
      }
    }
    },
    audio{
      asset->{
      _ref,
      url,
      extension,
      mimeType,
      metadata{
        dimensions
      }
    }
    },
    images[]{
      alt,
      caption,
      asset->{
      _ref,
      url,
      extension,
      mimeType,
      metadata{
        dimensions
      }
    },
      image{
        asset->{
      _ref,
      url,
      extension,
      mimeType,
      metadata{
        dimensions
      }
    }
      }
    },
    frames[]{
      alt,
      caption,
      asset->{
      _ref,
      url,
      extension,
      mimeType,
      metadata{
        dimensions
      }
    },
      image{
        asset->{
      _ref,
      url,
      extension,
      mimeType,
      metadata{
        dimensions
      }
    }
      }
    }
  }
}`;

export const siteSettingsQuery = groq`*[_type == "siteSettings"] | order(_updatedAt desc)[0] {
  ...
}`;
